"""Alembic migrations script template.

Revision ID: d2c623c6291a
Revises: 06f98e0a32e8
Create Date: 2026-05-25 10:27:23.983870+08:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c623c6291a'
down_revision: Union[str, None] = '06f98e0a32e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_reports', 'mentioned_task_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='该日报关联的 SprintTask UUID 列表(字符串形式)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('key_results', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='单位:ms / % / 个 / 元 等',
               existing_nullable=True)
    op.alter_column('key_results', 'description',
               existing_type=sa.TEXT(),
               comment='KR 详细描述,给 AI 抽取进度时提供上下文',
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='站内信已读时间;NULL 表示未读',
               existing_nullable=True)
    op.alter_column('users', 'dingtalk_userid',
               existing_type=sa.VARCHAR(length=64),
               comment='钉钉 userid，精准推送通知用',
               existing_nullable=True)
    op.drop_constraint('users_dingtalk_userid_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_dingtalk_userid'), 'users', ['dingtalk_userid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_dingtalk_userid'), table_name='users')
    op.create_unique_constraint('users_dingtalk_userid_key', 'users', ['dingtalk_userid'])
    op.alter_column('users', 'dingtalk_userid',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='钉钉 userid，精准推送通知用',
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='站内信已读时间;NULL 表示未读',
               existing_nullable=True)
    op.alter_column('key_results', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='KR 详细描述,给 AI 抽取进度时提供上下文',
               existing_nullable=True)
    op.alter_column('key_results', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='单位:ms / % / 个 / 元 等',
               existing_nullable=True)
    op.alter_column('daily_reports', 'mentioned_task_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='该日报关联的 SprintTask UUID 列表(字符串形式)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###
